[package]
name = "day5p1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
text_io = "0.1.12"
thiserror = "1.0.38"
type-cli = "0.0.3"
